-- AUTO-GENERATED by Theoremforces. Do not edit by hand.
-- Challenge: nat-mul-zero
-- Submission: cmpid8zpn0001wo1rbimwgk5y

import Mathlib

namespace Theoremforces.Challenges.User.U_nat_mul_zero.Submissions.Submission_cmpid8zpn0001wo1rbimwgk5y

-- ┌── USER SUBMISSION BODY (verbatim) ─────────────────────
-- The app appends:
--   def solution_target : ∀ (n : Nat), n * 0 = 0 := answer
-- so define `answer` with that type.

theorem answer (n : Nat) : n * 0 = 0 := by
  exact Nat.mul_zero n

-- └── USER SUBMISSION BODY END ────────────────────────────

/-- App-appended type check. Refuses to compile unless
    `answer` has type `∀ (n : Nat), n * 0 = 0`. -/
def solution_target : ∀ (n : Nat), n * 0 = 0 := answer

#print axioms solution_target

end Theoremforces.Challenges.User.U_nat_mul_zero.Submissions.Submission_cmpid8zpn0001wo1rbimwgk5y
