-- AUTO-GENERATED by Leanforces. Do not edit by hand.
-- Challenge: nat-mul-zero
-- Submission: cmpicjsyu0001xp1rql5tkl17

import Mathlib

namespace Leanforces.Challenges.User.U_nat_mul_zero.Submissions.Submission_cmpicjsyu0001xp1rql5tkl17

-- ┌── USER SUBMISSION BODY (verbatim) ─────────────────────
-- The app appends:
--   def solution_target : ∀ (n : Nat), n * 0 = 0 := answer
-- so define `answer` with that type.

theorem answer (n : Nat) : n * 0 = 0 := by
  ring

-- └── USER SUBMISSION BODY END ────────────────────────────

/-- App-appended type check. Refuses to compile unless
    `answer` has type `∀ (n : Nat), n * 0 = 0`. -/
def solution_target : ∀ (n : Nat), n * 0 = 0 := answer

#print axioms solution_target

end Leanforces.Challenges.User.U_nat_mul_zero.Submissions.Submission_cmpicjsyu0001xp1rql5tkl17
