-- AUTO-GENERATED by Theoremforces. Do not edit by hand.
-- Challenge: calc-quadratic-lower-bound
-- Submission: cmpk00hmy000fwx1uywhejr7t

import Mathlib

namespace Theoremforces.Challenges.User.U_calc_quadratic_lower_bound.Submissions.Submission_cmpk00hmy000fwx1uywhejr7t

-- ┌── USER SUBMISSION BODY (verbatim) ─────────────────────
-- The app appends:
--   def solution_target : ∀ (b c x : ℝ), c - b ^ 2 / 4 ≤ x ^ 2 + b * x + c := answer
-- so define `answer` with that type.

theorem answer (b c x : ℝ) : c - b ^ 2 / 4 ≤ x ^ 2 + b * x + c := by
  simp


-- └── USER SUBMISSION BODY END ────────────────────────────

/-- App-appended type check. Refuses to compile unless
    `answer` has type `∀ (b c x : ℝ), c - b ^ 2 / 4 ≤ x ^ 2 + b * x + c`. -/
def solution_target : ∀ (b c x : ℝ), c - b ^ 2 / 4 ≤ x ^ 2 + b * x + c := answer

#print axioms solution_target

end Theoremforces.Challenges.User.U_calc_quadratic_lower_bound.Submissions.Submission_cmpk00hmy000fwx1uywhejr7t
