-- AUTO-GENERATED by Theoremforces. Do not edit by hand.
-- Challenge: nat-zero-mul
-- Submission: cmpikof360001vm1uygvmrmyn

import Mathlib

namespace Theoremforces.Challenges.User.U_nat_zero_mul.Submissions.Submission_cmpikof360001vm1uygvmrmyn

-- ┌── USER SUBMISSION BODY (verbatim) ─────────────────────
-- The app appends:
--   def solution_target : ∀ (n : Nat), 0 * n = 0 := answer
-- so define `answer` with that type.

theorem answer (n : Nat) : 0 * n = 0 := by
  ring


-- └── USER SUBMISSION BODY END ────────────────────────────

/-- App-appended type check. Refuses to compile unless
    `answer` has type `∀ (n : Nat), 0 * n = 0`. -/
def solution_target : ∀ (n : Nat), 0 * n = 0 := answer

#print axioms solution_target

end Theoremforces.Challenges.User.U_nat_zero_mul.Submissions.Submission_cmpikof360001vm1uygvmrmyn
