-- AUTO-GENERATED by ProofGarden Lean Judge. Do not edit by hand.
-- Challenge: C0001
-- Submission: cmpgy91u80001yrvvnde7ph60

import ProofGarden.Challenges.C0001.Statement
import Mathlib

namespace ProofGarden.Challenges.C0001.Submissions.Submission_cmpgy91u80001yrvvnde7ph60

-- ┌── USER SUBMISSION BODY (verbatim) ─────────────────────
theorem not_answer (n : Nat) : n + 0 = n := Nat.add_zero n
-- └── USER SUBMISSION BODY END ────────────────────────────

/-- App-appended type check. Refuses to compile unless
    `answer` has type `∀ (n : Nat), n + 0 = n`. -/
def solution_target : ∀ (n : Nat), n + 0 = n := answer

#print axioms solution_target

end ProofGarden.Challenges.C0001.Submissions.Submission_cmpgy91u80001yrvvnde7ph60
